
-- ============================================================
-- HISTORIAL DE REPROGRAMACIÓN
-- ============================================================

CREATE SEQUENCE DATA.SQ_MTTO_HISTORIAL_REPROG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DATA.T_MTTO_HISTORIAL_REPROG (
    ID_HISTORIAL     NUMBER           NOT NULL,
    ID_OT            NUMBER           NOT NULL,
    FECHA_ORIGINAL   DATE,
    FECHA_REASIGNADA DATE             NOT NULL,
    REASIGNADO_POR   VARCHAR2(100 BYTE) NOT NULL,
    FECHA_CAMBIO     DATE DEFAULT SYSDATE NOT NULL,
    MOTIVO           VARCHAR2(500 BYTE),
    CONSTRAINT T_MTTO_HISTORIAL_REPROG_PK PRIMARY KEY (ID_HISTORIAL),
    CONSTRAINT T_MTTO_HISTORIAL_OT_FK FOREIGN KEY (ID_OT)
        REFERENCES DATA.T_MTTO_ORDENES_TRABAJO (ID_OT)
);

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_HISTORIAL_REPROG
  BEFORE INSERT ON DATA.T_MTTO_HISTORIAL_REPROG FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_HISTORIAL_REPROG.NEXTVAL INTO :NEW.ID_HISTORIAL FROM SYS.DUAL; END;
/

COMMENT ON TABLE  DATA.T_MTTO_HISTORIAL_REPROG               IS 'Historial de reprogramaciones de OTs para KPI de cumplimiento de planificación';
COMMENT ON COLUMN DATA.T_MTTO_HISTORIAL_REPROG.FECHA_ORIGINAL   IS 'Fecha planificada original antes del cambio (NULL si la OT no tenía fecha previa)';
COMMENT ON COLUMN DATA.T_MTTO_HISTORIAL_REPROG.FECHA_REASIGNADA IS 'Nueva fecha asignada en la reprogramación';
COMMENT ON COLUMN DATA.T_MTTO_HISTORIAL_REPROG.MOTIVO           IS 'Razón opcional de la reprogramación';
