-- ============================================================
-- DDL COMPLETO: MÓDULO MANTENIMIENTO ZAIMELLA
-- Schema: DATA
-- Convención: secuencias SQ_MTTO_* / triggers TG_MTTO_*
-- Los triggers asignan el ID automáticamente (no incluir en INSERT)
-- ============================================================
-- ORDEN DE EJECUCIÓN:
--   1. Secuencias
--   2. Tablas de catálogo (sin FK)
--   3. Tablas principales (con FK)
--   4. Triggers
--   5. Datos de catálogo (seed)
-- ============================================================

-- ============================================================
-- PASO 1: SECUENCIAS
-- ============================================================

CREATE SEQUENCE DATA.SQ_MTTO_TIPOS_ACTIVO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_ESTADOS_ACTIVO  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_ESTADOS_OT      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_PRIORIDADES     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_ACTIVOS         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_PUNTOS_MEDICION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_LECTURAS_USO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_PLANES          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_TAREAS_PLAN     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_ERP_REPUESTOS       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_REPUESTOS_PLAN  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_ORDENES_TRABAJO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_CHECKLIST_OT    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DATA.SQ_MTTO_SOLICITUDES     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- PASO 2: TABLAS DE CATÁLOGO (sin dependencias FK)
-- ============================================================

CREATE TABLE DATA.T_MTTO_TIPOS_ACTIVO (
    ID_TIPO_ACTIVO  NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    NOMBRE          VARCHAR2(100 BYTE) NOT NULL,
    DESCRIPCION     VARCHAR2(500 BYTE),
    CONSTRAINT T_MTTO_TIPOS_ACTIVO_PK PRIMARY KEY (ID_TIPO_ACTIVO)
);

CREATE TABLE DATA.T_MTTO_ESTADOS_ACTIVO (
    ID_ESTADO       NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    NOMBRE          VARCHAR2(50 BYTE) NOT NULL,
    COLOR_HEX       VARCHAR2(7 BYTE),
    ES_OPERATIVO    VARCHAR2(1 BYTE) DEFAULT 'S',
    CONSTRAINT T_MTTO_ESTADOS_ACTIVO_PK PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE DATA.T_MTTO_ESTADOS_OT (
    ID_ESTADO_OT    NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    NOMBRE          VARCHAR2(50 BYTE) NOT NULL,
    CODIGO          VARCHAR2(20 BYTE) NOT NULL,
    COLOR_HEX       VARCHAR2(7 BYTE),
    ORDEN_KANBAN    NUMBER,
    ES_ESTADO_FINAL VARCHAR2(1 BYTE) DEFAULT 'N',
    CONSTRAINT T_MTTO_ESTADOS_OT_PK PRIMARY KEY (ID_ESTADO_OT)
);

CREATE TABLE DATA.T_MTTO_PRIORIDADES (
    ID_PRIORIDAD         NUMBER          NOT NULL,
    CODIGO_COMPANIA      VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    NOMBRE               VARCHAR2(50 BYTE) NOT NULL,
    NIVEL                NUMBER          NOT NULL,
    COLOR_HEX            VARCHAR2(7 BYTE),
    TIEMPO_RESPUESTA_HRS NUMBER,
    CONSTRAINT T_MTTO_PRIORIDADES_PK PRIMARY KEY (ID_PRIORIDAD)
);

CREATE TABLE DATA.T_ERP_REPUESTOS_VW (
    ID_REPUESTO     NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    CODIGO_ERP      VARCHAR2(50 BYTE) NOT NULL,
    DESCRIPCION     VARCHAR2(300 BYTE) NOT NULL,
    UM              VARCHAR2(20 BYTE) DEFAULT 'UN',
    COSTO_PROMEDIO  NUMBER DEFAULT 0,
    STOCK_ACTUAL    NUMBER DEFAULT 0,
    CONSTRAINT T_ERP_REPUESTOS_VW_PK PRIMARY KEY (ID_REPUESTO),
    CONSTRAINT T_ERP_REPUESTOS_UK  UNIQUE (CODIGO_ERP)
);

-- ============================================================
-- PASO 3: TABLAS PRINCIPALES
-- ============================================================

CREATE TABLE DATA.T_MTTO_ACTIVOS (
    ID_ACTIVO       NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    CODIGO_ACTIVO   VARCHAR2(30 BYTE) NOT NULL,
    NOMBRE          VARCHAR2(200 BYTE) NOT NULL,
    DESCRIPCION     VARCHAR2(4000 BYTE),
    ID_TIPO_ACTIVO  NUMBER          NOT NULL,
    ID_ESTADO       NUMBER          NOT NULL,
    ID_ACTIVO_PADRE NUMBER,
    ID_PLANTA       NUMBER          NOT NULL,
    ID_AREA         NUMBER,
    ID_LINEA        NUMBER,
    NIVEL_JERARQUIA NUMBER          NOT NULL,
    CRITICIDAD      VARCHAR2(1 BYTE) DEFAULT 'C',
    MARCA           VARCHAR2(100 BYTE),
    MODELO          VARCHAR2(100 BYTE),
    NUMERO_SERIE    VARCHAR2(100 BYTE),
    ANIO_FABRICACION NUMBER,
    CREADO_POR      VARCHAR2(100 BYTE) NOT NULL,
    FECHA_CREACION  DATE DEFAULT SYSDATE,
    CONSTRAINT T_MTTO_ACTIVOS_PK      PRIMARY KEY (ID_ACTIVO),
    CONSTRAINT T_MTTO_ACTIVOS_UK      UNIQUE (CODIGO_ACTIVO),
    CONSTRAINT T_MTTO_ACTIVOS_TIPO_FK FOREIGN KEY (ID_TIPO_ACTIVO)
        REFERENCES DATA.T_MTTO_TIPOS_ACTIVO (ID_TIPO_ACTIVO),
    CONSTRAINT T_MTTO_ACTIVOS_EST_FK  FOREIGN KEY (ID_ESTADO)
        REFERENCES DATA.T_MTTO_ESTADOS_ACTIVO (ID_ESTADO),
    CONSTRAINT T_MTTO_ACTIVOS_PAD_FK  FOREIGN KEY (ID_ACTIVO_PADRE)
        REFERENCES DATA.T_MTTO_ACTIVOS (ID_ACTIVO)
);

CREATE TABLE DATA.T_MTTO_PUNTOS_MEDICION (
    ID_PUNTO        NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_ACTIVO       NUMBER          NOT NULL,
    NOMBRE          VARCHAR2(100 BYTE) NOT NULL,
    UNIDAD_MEDIDA   VARCHAR2(20 BYTE) NOT NULL,
    VALOR_ACUMULADO NUMBER DEFAULT 0,
    CONSTRAINT T_MTTO_PUNTOS_MEDICION_PK PRIMARY KEY (ID_PUNTO),
    CONSTRAINT T_MTTO_PUNTOS_ACTIVO_FK   FOREIGN KEY (ID_ACTIVO)
        REFERENCES DATA.T_MTTO_ACTIVOS (ID_ACTIVO)
);

CREATE TABLE DATA.T_MTTO_LECTURAS_USO (
    ID_LECTURA      NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_PUNTO        NUMBER          NOT NULL,
    VALOR_LEIDO     NUMBER          NOT NULL,
    FECHA_LECTURA   DATE DEFAULT SYSDATE,
    REGISTRADO_POR  VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT T_MTTO_LECTURAS_USO_PK    PRIMARY KEY (ID_LECTURA),
    CONSTRAINT T_MTTO_LECTURAS_PUNTO_FK  FOREIGN KEY (ID_PUNTO)
        REFERENCES DATA.T_MTTO_PUNTOS_MEDICION (ID_PUNTO)
);

CREATE TABLE DATA.T_MTTO_PLANES (
    ID_PLAN             NUMBER          NOT NULL,
    CODIGO_COMPANIA     VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_ACTIVO           NUMBER          NOT NULL,
    NOMBRE              VARCHAR2(200 BYTE) NOT NULL,
    TIPO_FRECUENCIA     VARCHAR2(20 BYTE) NOT NULL,
    FRECUENCIA_VALOR    NUMBER          NOT NULL,
    ID_PUNTO_MEDICION   NUMBER,
    CONSTRAINT T_MTTO_PLANES_PK          PRIMARY KEY (ID_PLAN),
    CONSTRAINT T_MTTO_PLANES_ACTIVO_FK   FOREIGN KEY (ID_ACTIVO)
        REFERENCES DATA.T_MTTO_ACTIVOS (ID_ACTIVO),
    CONSTRAINT T_MTTO_PLANES_PUNTO_FK    FOREIGN KEY (ID_PUNTO_MEDICION)
        REFERENCES DATA.T_MTTO_PUNTOS_MEDICION (ID_PUNTO)
);

CREATE TABLE DATA.T_MTTO_TAREAS_PLAN (
    ID_TAREA_PLAN    NUMBER          NOT NULL,
    CODIGO_COMPANIA  VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_PLAN          NUMBER          NOT NULL,
    SECUENCIA        NUMBER          NOT NULL,
    DESCRIPCION      VARCHAR2(1000 BYTE) NOT NULL,
    REQUIERE_MEDICION VARCHAR2(1 BYTE) DEFAULT 'N',
    CONSTRAINT T_MTTO_TAREAS_PLAN_PK     PRIMARY KEY (ID_TAREA_PLAN),
    CONSTRAINT T_MTTO_TAREAS_PLAN_FK     FOREIGN KEY (ID_PLAN)
        REFERENCES DATA.T_MTTO_PLANES (ID_PLAN)
);

CREATE TABLE DATA.T_MTTO_REPUESTOS_PLAN (
    ID_REPUESTO_PLAN NUMBER          NOT NULL,
    CODIGO_COMPANIA  VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_PLAN          NUMBER          NOT NULL,
    ID_REPUESTO      NUMBER          NOT NULL,
    CANTIDAD         NUMBER          NOT NULL,
    CONSTRAINT T_MTTO_REPUESTOS_PLAN_PK  PRIMARY KEY (ID_REPUESTO_PLAN),
    CONSTRAINT T_MTTO_REP_PLAN_PLAN_FK   FOREIGN KEY (ID_PLAN)
        REFERENCES DATA.T_MTTO_PLANES (ID_PLAN),
    CONSTRAINT T_MTTO_REP_PLAN_REP_FK    FOREIGN KEY (ID_REPUESTO)
        REFERENCES DATA.T_ERP_REPUESTOS_VW (ID_REPUESTO)
);

CREATE TABLE DATA.T_MTTO_ORDENES_TRABAJO (
    ID_OT           NUMBER          NOT NULL,
    CODIGO_COMPANIA VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    NUMERO_OT       VARCHAR2(20 BYTE) NOT NULL,
    TIPO_OT         VARCHAR2(20 BYTE) NOT NULL,
    ID_PRIORIDAD    NUMBER          NOT NULL,
    ID_ESTADO_OT    NUMBER          NOT NULL,
    ID_ACTIVO       NUMBER          NOT NULL,
    DESCRIPCION     VARCHAR2(4000 BYTE) NOT NULL,
    FECHA_PROGRAMADA DATE,
    ASIGNADO_A      VARCHAR2(100 BYTE),
    CREADO_POR      VARCHAR2(100 BYTE) NOT NULL,
    FECHA_CREACION  DATE DEFAULT SYSDATE,
    CONSTRAINT T_MTTO_ORDENES_TRABAJO_PK  PRIMARY KEY (ID_OT),
    CONSTRAINT T_MTTO_OT_NUMERO_UK        UNIQUE (NUMERO_OT),
    CONSTRAINT T_MTTO_OT_PRIORIDAD_FK     FOREIGN KEY (ID_PRIORIDAD)
        REFERENCES DATA.T_MTTO_PRIORIDADES (ID_PRIORIDAD),
    CONSTRAINT T_MTTO_OT_ESTADO_FK        FOREIGN KEY (ID_ESTADO_OT)
        REFERENCES DATA.T_MTTO_ESTADOS_OT (ID_ESTADO_OT),
    CONSTRAINT T_MTTO_OT_ACTIVO_FK        FOREIGN KEY (ID_ACTIVO)
        REFERENCES DATA.T_MTTO_ACTIVOS (ID_ACTIVO)
);

CREATE TABLE DATA.T_MTTO_CHECKLIST_OT (
    ID_CHECKLIST        NUMBER          NOT NULL,
    CODIGO_COMPANIA     VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_OT               NUMBER          NOT NULL,
    SECUENCIA           NUMBER          NOT NULL,
    DESCRIPCION         VARCHAR2(1000 BYTE) NOT NULL,
    COMPLETADO          VARCHAR2(1 BYTE) DEFAULT 'N',
    VALOR_MEDIDO        VARCHAR2(100 BYTE),
    OBSERVACION_TECNICO VARCHAR2(1000 BYTE),
    CONSTRAINT T_MTTO_CHECKLIST_OT_PK  PRIMARY KEY (ID_CHECKLIST),
    CONSTRAINT T_MTTO_CHECKLIST_OT_FK  FOREIGN KEY (ID_OT)
        REFERENCES DATA.T_MTTO_ORDENES_TRABAJO (ID_OT)
);

CREATE TABLE DATA.T_MTTO_SOLICITUDES (
    ID_SOLICITUD      NUMBER          NOT NULL,
    CODIGO_COMPANIA   VARCHAR2(10 BYTE) DEFAULT 'ZML_EC' NOT NULL,
    ID_ACTIVO         NUMBER          NOT NULL,
    DESCRIPCION_FALLA VARCHAR2(2000 BYTE) NOT NULL,
    PRIORIDAD_SUGERIDA VARCHAR2(50 BYTE),
    ESTADO            VARCHAR2(20 BYTE) DEFAULT 'PENDIENTE',
    REPORTADO_POR     VARCHAR2(100 BYTE) NOT NULL,
    FECHA_REPORTE     DATE DEFAULT SYSDATE,
    ID_OT_GENERADA    NUMBER,
    CONSTRAINT T_MTTO_SOLICITUDES_PK     PRIMARY KEY (ID_SOLICITUD),
    CONSTRAINT T_MTTO_SOL_ACTIVO_FK      FOREIGN KEY (ID_ACTIVO)
        REFERENCES DATA.T_MTTO_ACTIVOS (ID_ACTIVO),
    CONSTRAINT T_MTTO_SOL_OT_FK          FOREIGN KEY (ID_OT_GENERADA)
        REFERENCES DATA.T_MTTO_ORDENES_TRABAJO (ID_OT)
);

-- ============================================================
-- PASO 4: TRIGGERS (auto-asignación de ID)
-- ============================================================

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_TIPOS_ACTIVO
  BEFORE INSERT ON DATA.T_MTTO_TIPOS_ACTIVO FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_TIPOS_ACTIVO.NEXTVAL INTO :NEW.ID_TIPO_ACTIVO FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_ESTADOS_ACTIVO
  BEFORE INSERT ON DATA.T_MTTO_ESTADOS_ACTIVO FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_ESTADOS_ACTIVO.NEXTVAL INTO :NEW.ID_ESTADO FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_ESTADOS_OT
  BEFORE INSERT ON DATA.T_MTTO_ESTADOS_OT FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_ESTADOS_OT.NEXTVAL INTO :NEW.ID_ESTADO_OT FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_PRIORIDADES
  BEFORE INSERT ON DATA.T_MTTO_PRIORIDADES FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_PRIORIDADES.NEXTVAL INTO :NEW.ID_PRIORIDAD FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_ERP_REPUESTOS
  BEFORE INSERT ON DATA.T_ERP_REPUESTOS_VW FOR EACH ROW
BEGIN SELECT DATA.SQ_ERP_REPUESTOS.NEXTVAL INTO :NEW.ID_REPUESTO FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_ACTIVOS
  BEFORE INSERT ON DATA.T_MTTO_ACTIVOS FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_ACTIVOS.NEXTVAL INTO :NEW.ID_ACTIVO FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_PUNTOS_MEDICION
  BEFORE INSERT ON DATA.T_MTTO_PUNTOS_MEDICION FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_PUNTOS_MEDICION.NEXTVAL INTO :NEW.ID_PUNTO FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_LECTURAS_USO
  BEFORE INSERT ON DATA.T_MTTO_LECTURAS_USO FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_LECTURAS_USO.NEXTVAL INTO :NEW.ID_LECTURA FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_PLANES
  BEFORE INSERT ON DATA.T_MTTO_PLANES FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_PLANES.NEXTVAL INTO :NEW.ID_PLAN FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_TAREAS_PLAN
  BEFORE INSERT ON DATA.T_MTTO_TAREAS_PLAN FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_TAREAS_PLAN.NEXTVAL INTO :NEW.ID_TAREA_PLAN FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_REPUESTOS_PLAN
  BEFORE INSERT ON DATA.T_MTTO_REPUESTOS_PLAN FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_REPUESTOS_PLAN.NEXTVAL INTO :NEW.ID_REPUESTO_PLAN FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_ORDENES_TRABAJO
  BEFORE INSERT ON DATA.T_MTTO_ORDENES_TRABAJO FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_ORDENES_TRABAJO.NEXTVAL INTO :NEW.ID_OT FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_CHECKLIST_OT
  BEFORE INSERT ON DATA.T_MTTO_CHECKLIST_OT FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_CHECKLIST_OT.NEXTVAL INTO :NEW.ID_CHECKLIST FROM SYS.DUAL; END;
/

CREATE OR REPLACE TRIGGER DATA.TG_MTTO_SOLICITUDES
  BEFORE INSERT ON DATA.T_MTTO_SOLICITUDES FOR EACH ROW
BEGIN SELECT DATA.SQ_MTTO_SOLICITUDES.NEXTVAL INTO :NEW.ID_SOLICITUD FROM SYS.DUAL; END;
/

-- ============================================================
-- PASO 5: DATOS DE CATÁLOGO (seed inicial)
-- ============================================================

-- Estados de Órdenes de Trabajo
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('Abierta',             'OPEN',     '#3498db', 1, 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('En Progreso',         'WIP',      '#f39c12', 2, 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('Esperando Material',  'WAIT_MAT', '#e74c3c', 3, 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('Cerrada (Completada)','CLOSE',    '#00a651', 4, 'S');

-- Prioridades
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Crítica (Paro de Planta)', 1, '#c0392b', 1);
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Alta',                     2, '#e67e22', 4);
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Media',                    3, '#f1c40f', 24);
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Baja',                     4, '#95a5a6', 72);

-- Tipos de Activo
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Planta de Producción',  'Planta entera');
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Línea de Ensamblaje',   'Línea de producción');
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Máquina Principal',     'Activo formador central');
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Componente Menor',      'Parte o Pieza');

-- Estados de Activo
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('Operativo',          '#00a651', 'S');
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('Falla / Detenido',   '#e74c3c', 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('Stand-By',           '#f39c12', 'S');
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('En Reparación',      '#3498db', 'N');

COMMIT;

-- ============================================================
-- PASO 6: PERMISOS DE ACCESO AL SCHEMA MNT_CORE (si aplica)
-- Si el backend conecta con un usuario distinto a DATA, ejecutar:
-- ============================================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_TIPOS_ACTIVO   TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_ESTADOS_ACTIVO  TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_ESTADOS_OT      TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_PRIORIDADES      TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_ACTIVOS          TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_PUNTOS_MEDICION  TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_LECTURAS_USO     TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_PLANES           TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_TAREAS_PLAN      TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_ERP_REPUESTOS_VW     TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_REPUESTOS_PLAN   TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_ORDENES_TRABAJO  TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_CHECKLIST_OT     TO MNT_CORE;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATA.T_MTTO_SOLICITUDES      TO MNT_CORE;

-- ============================================================
-- VERIFICACIÓN FINAL
-- ============================================================
SELECT TABLE_NAME, NUM_ROWS
  FROM ALL_TABLES
 WHERE OWNER = 'DATA'
   AND TABLE_NAME LIKE 'T_MTTO_%' OR TABLE_NAME = 'T_ERP_REPUESTOS_VW'
 ORDER BY TABLE_NAME;
