-- ============================================================
-- DATOS DE PRUEBA: MÓDULO MANTENIMIENTO ZAIMELLA
-- Schema: DATA   Módulo: MTTO
-- ============================================================
-- INSTRUCCIONES:
--   1. Ejecutar primero el bloque LIMPIEZA (borra todo en orden)
--   2. Luego ejecutar el resto del script completo
-- ============================================================

-- ============================================================
-- LIMPIEZA (ejecutar primero — respeta orden de FKs)
-- ============================================================
DELETE FROM DATA.T_MTTO_SOLICITUDES;
DELETE FROM DATA.T_MTTO_CHECKLIST_OT;
DELETE FROM DATA.T_MTTO_REPUESTOS_PLAN;
DELETE FROM DATA.T_MTTO_ORDENES_TRABAJO;
DELETE FROM DATA.T_MTTO_LECTURAS_USO;
DELETE FROM DATA.T_MTTO_PUNTOS_MEDICION;
DELETE FROM DATA.T_MTTO_TAREAS_PLAN;
DELETE FROM DATA.T_MTTO_PLANES;
DELETE FROM DATA.T_ERP_REPUESTOS_VW;
DELETE FROM DATA.T_MTTO_ACTIVOS;
DELETE FROM DATA.T_MTTO_ESTADOS_OT;
DELETE FROM DATA.T_MTTO_PRIORIDADES;
DELETE FROM DATA.T_MTTO_TIPOS_ACTIVO;
DELETE FROM DATA.T_MTTO_ESTADOS_ACTIVO;
COMMIT;

-- ============================================================
-- PASO 1: CATÁLOGOS BASE
-- ============================================================

INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('Abierta',             'OPEN',     '#3498db', 1, 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('En Progreso',         'WIP',      '#f39c12', 2, 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('Esperando Material',  'WAIT_MAT', '#e74c3c', 3, 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_OT (NOMBRE, CODIGO, COLOR_HEX, ORDEN_KANBAN, ES_ESTADO_FINAL)
VALUES ('Cerrada (Completada)','CLOSE',    '#00a651', 4, 'S');

INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Crítica (Paro de Planta)', 1, '#c0392b', 1);
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Alta',                     2, '#e67e22', 4);
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Media',                    3, '#f1c40f', 24);
INSERT INTO DATA.T_MTTO_PRIORIDADES (NOMBRE, NIVEL, COLOR_HEX, TIEMPO_RESPUESTA_HRS)
VALUES ('Baja',                     4, '#95a5a6', 72);

INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Planta de Producción', 'Planta entera');
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Línea de Ensamblaje',  'Línea de producción');
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Máquina Principal',    'Activo formador central');
INSERT INTO DATA.T_MTTO_TIPOS_ACTIVO (NOMBRE, DESCRIPCION)
VALUES ('Componente Menor',     'Parte o Pieza');

INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('Operativo',        '#00a651', 'S');
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('Falla / Detenido', '#e74c3c', 'N');
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('Stand-By',         '#f39c12', 'S');
INSERT INTO DATA.T_MTTO_ESTADOS_ACTIVO (NOMBRE, COLOR_HEX, ES_OPERATIVO)
VALUES ('En Reparación',    '#3498db', 'N');

COMMIT;

-- ============================================================
-- PASO 2: REPUESTOS ERP
-- ============================================================

INSERT INTO DATA.T_ERP_REPUESTOS_VW (CODIGO_ERP, DESCRIPCION, UM, COSTO_PROMEDIO, STOCK_ACTUAL)
VALUES ('REP-DIE-100',  'Cuchilla Corte Troquel Pañal',                  'UN', 5400.0, 2.0);
INSERT INTO DATA.T_ERP_REPUESTOS_VW (CODIGO_ERP, DESCRIPCION, UM, COSTO_PROMEDIO, STOCK_ACTUAL)
VALUES ('REP-BRG-20RS', 'Rodamiento Sellado SKF',                         'UN',   45.0, 25.0);
INSERT INTO DATA.T_ERP_REPUESTOS_VW (CODIGO_ERP, DESCRIPCION, UM, COSTO_PROMEDIO, STOCK_ACTUAL)
VALUES ('LUB-FOOD-5W',  'Lubricante Grado Alimenticio / Cosmético (Lt)', 'LT',   18.0, 10.0);
INSERT INTO DATA.T_ERP_REPUESTOS_VW (CODIGO_ERP, DESCRIPCION, UM, COSTO_PROMEDIO, STOCK_ACTUAL)
VALUES ('ELEC-RES-5KW', 'Resistencia Selladora de Paquetes',              'UN',   85.0,  0.0);

COMMIT;

-- ============================================================
-- PASO 3: ACTIVOS (jerárquico — respetar este orden)
-- Las subconsultas de catálogo usan ROWNUM = 1 para garantizar
-- una sola fila aunque hubiera duplicados previos.
-- ============================================================

-- Nivel 1: Plantas
INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, DESCRIPCION, ID_TIPO_ACTIVO, ID_ESTADO, CRITICIDAD, MARCA, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('PL-BABY-01', 'Planta Central Pañales Infantiles', 'Fábrica principal de absorbentes',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Planta de Producción' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    'A', 'Varios', 1, 1, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, DESCRIPCION, ID_TIPO_ACTIVO, ID_ESTADO, CRITICIDAD, MARCA, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('PL-ADULT-02', 'Planta Pañales Adulto', 'Fábrica de pañales incontinencia',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Planta de Producción' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    'A', 'Diatec', 2, 1, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, DESCRIPCION, ID_TIPO_ACTIVO, ID_ESTADO, CRITICIDAD, MARCA, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('PL-PETS-03', 'Planta Pads Mascotas', 'Fábrica de sabanillas para perros',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Planta de Producción' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    'B', 'Fameccanica', 3, 1, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, DESCRIPCION, ID_TIPO_ACTIVO, ID_ESTADO, CRITICIDAD, MARCA, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('PL-COSM-04', 'Planta Cosmética y Líquidos', 'Producción de Toallitas Húmedas y Shampoo',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Planta de Producción' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    'A', 'Bausch', 4, 1, 'sistema');

COMMIT;

-- Nivel 2: Líneas
INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('LIN-BABY-PA01', 'Línea Absorbentes Premium',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Línea de Ensamblaje' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'PL-BABY-01'),
    'A', 1, 2, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('LIN-ADU-01', 'Línea Pañales Incontinencia',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Línea de Ensamblaje' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'PL-ADULT-02'),
    'A', 2, 2, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('LIN-PET-01', 'Línea Sabanillas de Entrenamiento',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Línea de Ensamblaje' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'PL-PETS-03'),
    'B', 3, 2, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('LIN-WET-W01', 'Línea Toallitas Húmedas',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Línea de Ensamblaje' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'PL-COSM-04'),
    'A', 4, 2, 'sistema');

COMMIT;

-- Nivel 3: Máquinas
INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-MOL-01', 'Molino Formador de Fluff (Celulosa)',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-BABY-PA01'),
    'A', 1, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-SAP-01', 'Aplicador Dosificador de SAP',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-BABY-PA01'),
    'A', 1, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-CORT-01', 'Cuchilla Corte Final (Die Cutter)',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-BABY-PA01'),
    'A', 1, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-EMP-01', 'Bolsadora Automática Gevas',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-BABY-PA01'),
    'B', 1, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-FORM-A01', 'Tambor Formador Adultos (Diatec)',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-ADU-01'),
    'A', 2, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-CUT-P01', 'Corte Guillotina Rotary (Pads)',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-PET-01'),
    'B', 3, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-MIX-01', 'Tanque Mezclador de Loción Infantil',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-WET-W01'),
    'A', 4, 3, 'sistema');

INSERT INTO DATA.T_MTTO_ACTIVOS (CODIGO_ACTIVO, NOMBRE, ID_TIPO_ACTIVO, ID_ESTADO, ID_ACTIVO_PADRE, CRITICIDAD, ID_PLANTA, NIVEL_JERARQUIA, CREADO_POR)
VALUES ('MQ-HIL-01', 'Cortadora Dobladora Spunlace',
    (SELECT ID_TIPO_ACTIVO FROM DATA.T_MTTO_TIPOS_ACTIVO WHERE NOMBRE = 'Máquina Principal' AND ROWNUM = 1),
    (SELECT ID_ESTADO FROM DATA.T_MTTO_ESTADOS_ACTIVO WHERE NOMBRE = 'Operativo' AND ROWNUM = 1),
    (SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO = 'LIN-WET-W01'),
    'A', 4, 3, 'sistema');

COMMIT;

-- ============================================================
-- PASO 4: PUNTOS DE MEDICIÓN
-- ============================================================

INSERT INTO DATA.T_MTTO_PUNTOS_MEDICION (ID_ACTIVO, NOMBRE, UNIDAD_MEDIDA, VALOR_ACUMULADO)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'), 'Contador de Pañales (Millones)', 'UNIDADES', 45.2);
INSERT INTO DATA.T_MTTO_PUNTOS_MEDICION (ID_ACTIVO, NOMBRE, UNIDAD_MEDIDA, VALOR_ACUMULADO)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01'),  'Horómetro Rotativo', 'HORAS', 3250);
INSERT INTO DATA.T_MTTO_PUNTOS_MEDICION (ID_ACTIVO, NOMBRE, UNIDAD_MEDIDA, VALOR_ACUMULADO)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MIX-01'),  'Lotes Procesados (Batches)', 'LOTES', 1560);
INSERT INTO DATA.T_MTTO_PUNTOS_MEDICION (ID_ACTIVO, NOMBRE, UNIDAD_MEDIDA, VALOR_ACUMULADO)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-HIL-01'),  'Horómetro de Cuchilla Cizalla', 'HORAS', 950);

COMMIT;

-- ============================================================
-- PASO 5: PLANES DE MANTENIMIENTO
-- ============================================================

INSERT INTO DATA.T_MTTO_PLANES (ID_ACTIVO, NOMBRE, TIPO_FRECUENCIA, FRECUENCIA_VALOR, ID_PUNTO_MEDICION)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),
    'Afilado y Ajuste de Cuchilla Corte (Die)', 'USO', 50,
    (SELECT ID_PUNTO FROM DATA.T_MTTO_PUNTOS_MEDICION WHERE ID_ACTIVO=(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01')));

INSERT INTO DATA.T_MTTO_PLANES (ID_ACTIVO, NOMBRE, TIPO_FRECUENCIA, FRECUENCIA_VALOR, ID_PUNTO_MEDICION)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01'),
    'Mantenimiento 4000h Molino Desfibrador', 'USO', 4000,
    (SELECT ID_PUNTO FROM DATA.T_MTTO_PUNTOS_MEDICION WHERE ID_ACTIVO=(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01')));

INSERT INTO DATA.T_MTTO_PLANES (ID_ACTIVO, NOMBRE, TIPO_FRECUENCIA, FRECUENCIA_VALOR, ID_PUNTO_MEDICION)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MIX-01'),
    'Sanitización Química y Lubricación', 'TIEMPO', 30, NULL);

INSERT INTO DATA.T_MTTO_PLANES (ID_ACTIVO, NOMBRE, TIPO_FRECUENCIA, FRECUENCIA_VALOR, ID_PUNTO_MEDICION)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-EMP-01'),
    'Reemplazo Mordaza Térmica (Alerta Rotura Stock)', 'TIEMPO', 180, NULL);

COMMIT;

-- ============================================================
-- PASO 6: BOM DE REPUESTOS POR PLAN
-- ============================================================

INSERT INTO DATA.T_MTTO_REPUESTOS_PLAN (ID_PLAN, ID_REPUESTO, CANTIDAD)
VALUES ((SELECT ID_PLAN FROM DATA.T_MTTO_PLANES WHERE NOMBRE LIKE 'Afilado%'),
        (SELECT ID_REPUESTO FROM DATA.T_ERP_REPUESTOS_VW WHERE CODIGO_ERP='REP-DIE-100'), 1);
INSERT INTO DATA.T_MTTO_REPUESTOS_PLAN (ID_PLAN, ID_REPUESTO, CANTIDAD)
VALUES ((SELECT ID_PLAN FROM DATA.T_MTTO_PLANES WHERE NOMBRE LIKE 'Mantenimiento 4000h%'),
        (SELECT ID_REPUESTO FROM DATA.T_ERP_REPUESTOS_VW WHERE CODIGO_ERP='REP-BRG-20RS'), 4);
INSERT INTO DATA.T_MTTO_REPUESTOS_PLAN (ID_PLAN, ID_REPUESTO, CANTIDAD)
VALUES ((SELECT ID_PLAN FROM DATA.T_MTTO_PLANES WHERE NOMBRE LIKE 'Sanitización%'),
        (SELECT ID_REPUESTO FROM DATA.T_ERP_REPUESTOS_VW WHERE CODIGO_ERP='LUB-FOOD-5W'), 5);
INSERT INTO DATA.T_MTTO_REPUESTOS_PLAN (ID_PLAN, ID_REPUESTO, CANTIDAD)
VALUES ((SELECT ID_PLAN FROM DATA.T_MTTO_PLANES WHERE NOMBRE LIKE 'Reemplazo Mordaza%'),
        (SELECT ID_REPUESTO FROM DATA.T_ERP_REPUESTOS_VW WHERE CODIGO_ERP='ELEC-RES-5KW'), 2);

COMMIT;

-- ============================================================
-- PASO 7: ÓRDENES DE TRABAJO
-- TRUNC(SYSDATE,'IW') = lunes de esta semana
-- +7=lun, +8=mar, +9=mie, +10=jue, +11=vie, +14=lun siguiente
-- ============================================================

-- OTs sin fecha planificada
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,CREADO_POR)
VALUES ('OT-2026-0150','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-EMP-01'),'Reemplazo preventivo de mordazas térmicas según calendario.','sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,ASIGNADO_A,FECHA_PROGRAMADA,CREADO_POR)
VALUES ('OT-2026-0151','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='WIP'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01'),'Cambio de rodamiento SKF de molino de celulosa (Alcanzó 4000h).','cvaca',SYSDATE,'sistema');
COMMIT;

INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0151'),1,'Bloquear energía eléctrica y neumática (LOTO)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0151'),2,'Extracción de collar de rodamiento del eje de martillos');
COMMIT;

-- Lunes
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0200','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01'),'Lubricación semanal de ejes y martillos del molino de fluff.',TRUNC(SYSDATE,'IW')+7,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0201','CORRECTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-SAP-01'),'Limpieza de boquillas dosificadoras de SAP bloqueadas.',TRUNC(SYSDATE,'IW')+7,'sistema');
COMMIT;
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0200'),1,'Bloquear energía eléctrica (LOTO)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0200'),2,'Aplicar grasa SKF LGMT-2 en 4 puntos de lubricación');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0200'),3,'Verificar temperatura de rodamientos post-arranque (<55°C)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0201'),1,'Purgar sistema neumático del dosificador');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0201'),2,'Reemplazar boquilla dañada con repuesto en almacén');
COMMIT;

-- Martes
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0202','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),'Afilado programado de cuchilla troquel (ciclo 50M unidades).',TRUNC(SYSDATE,'IW')+8,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0203','CORRECTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-FORM-A01'),'Tambor formador genera absorbente irregular. Ajuste de vacío y guías.',TRUNC(SYSDATE,'IW')+8,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0204','PREDICTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=4),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MIX-01'),'Análisis de vibración en agitador principal del tanque mezclador.',TRUNC(SYSDATE,'IW')+8,'sistema');
COMMIT;
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0202'),1,'Desmontar cuchilla con útil de extracción');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0202'),2,'Verificar ángulo de corte (22.5° ± 0.5°)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0202'),3,'Prueba de corte con 100 pañales antes de producción');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0203'),1,'Medir caudal de vacío actual (referencia: -450 mbar)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0203'),2,'Ajustar guías laterales al espesor de fluff correcto');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0204'),1,'Instalar sensor de vibración en eje agitador');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0204'),2,'Registrar espectro FFT en rango 10-1000 Hz');
COMMIT;

-- Miércoles
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0205','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-EMP-01'),'Reemplazo de mordazas térmicas de sellado lateral. Alerta stock resistencias.',TRUNC(SYSDATE,'IW')+9,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0206','CORRECTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=1),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-HIL-01'),'Cuchilla Spunlace mellada — paro inminente si no se interviene.',TRUNC(SYSDATE,'IW')+9,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0207','EMERGENCIA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=1),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01'),'PARO NO PLANIFICADO: falla de sensor de temperatura en cámara de molienda.',TRUNC(SYSDATE,'IW')+9,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0208','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=4),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CUT-P01'),'Revisión mensual de guillotina rotary: tensión de cuchilla y alineación.',TRUNC(SYSDATE,'IW')+9,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0209','PREDICTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-SAP-01'),'Termografía eléctrica en tablero de control del dosificador SAP.',TRUNC(SYSDATE,'IW')+9,'sistema');
-- Escenario multi-OT miércoles
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0230','EMERGENCIA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=1),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),'EMERGENCIA eléctrica: variador de frecuencia se disparó por sobrecorriente. Línea PA01 detenida.',TRUNC(SYSDATE,'IW')+9,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0231','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),'Mantenimiento preventivo semanal Die Cutter: limpieza de guías, ajuste de presión y lubricación.',TRUNC(SYSDATE,'IW')+9,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0232','PREDICTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),'Análisis termográfico del tablero eléctrico del Die Cutter (predictivo mensual).',TRUNC(SYSDATE,'IW')+9,'sistema');
COMMIT;

INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0205'),1,'Confirmar disponibilidad de resistencias en almacén');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0205'),2,'Desconectar alimentación 220V de mordazas');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0205'),3,'Instalar resistencias nuevas y verificar temperatura de sellado (160°C)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0206'),1,'Cambiar cuchilla Spunlace (requiere 2 técnicos)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0206'),2,'Calibrar presión de corte a 8 bar');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0207'),1,'Identificar sensor defectuoso en tablero eléctrico');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0207'),2,'Reemplazar sensor PT100 y verificar lectura (70°C ± 2°C)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0207'),3,'Reiniciar PLC y confirmar señal en SCADA');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0208'),1,'Medir tensión de cuchilla con tensiómetro');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0209'),1,'Tomar termografía con cámara FLIR en tablero principal');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0209'),2,'Reportar puntos calientes > 60°C para gestión correctiva');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0230'),1,'Bloquear LOTO en tablero principal del Die Cutter');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0230'),2,'Medir resistencia de aislamiento del motor (>1 MΩ)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0230'),3,'Revisar parámetros del variador (corriente nominal: 38A)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0230'),4,'Resetear falla F0001 en variador y arranque de prueba');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0231'),1,'Limpiar guías de chapa con solvente dieléctrico');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0231'),2,'Verificar presión de corte con manómetro de banco (7.5 ± 0.3 bar)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0231'),3,'Aplicar grasa Molykote G-900 en 6 puntos de cojinetes');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0232'),1,'Capturar imagen termográfica del tablero con cámara FLIR E86');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0232'),2,'Comparar con línea base del mes anterior');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0232'),3,'Emitir informe si delta de temperatura > 15°C en algún componente');
COMMIT;

-- Jueves
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0210','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-FORM-A01'),'Cambio de sellos y O-rings en sistema de vacío del tambor formador adultos.',TRUNC(SYSDATE,'IW')+10,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0211','CORRECTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MIX-01'),'Fuga de loción en brida de salida del tanque mezclador. Reajuste de pernos.',TRUNC(SYSDATE,'IW')+10,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0212','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=4),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-HIL-01'),'Lubricación bimestral de rodillos tensores de tela spunlace.',TRUNC(SYSDATE,'IW')+10,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0213','PREDICTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),'Ultrasonido en rodamientos de eje principal de cortadora (detectar desgaste).',TRUNC(SYSDATE,'IW')+10,'sistema');
COMMIT;
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0210'),1,'Despresurizar sistema de vacío');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0210'),2,'Reemplazar 8 O-rings de sección 5mm con kit de repuesto');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0211'),1,'Localizar brida con fuga mediante inspección visual');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0211'),2,'Apretar pernos M16 a torque especificado (45 Nm)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0212'),1,'Aplicar lubricante cosmético grado USDA en 6 rodillos');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0213'),1,'Medir decibelios ultrasónicos en 4 rodamientos');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0213'),2,'Registrar valores en base de datos histórica');
COMMIT;

-- Viernes
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0214','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MOL-01'),'Mantenimiento mayor 4000h: cambio de rodamientos SKF en eje de martillos.',TRUNC(SYSDATE,'IW')+11,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0215','CORRECTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-SAP-01'),'Sensor de flujo SAP da lectura errática. Reemplazo de sensor Endress+Hauser.',TRUNC(SYSDATE,'IW')+11,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0216','EMERGENCIA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=1),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-EMP-01'),'EMERGENCIA: resistencia de sellado inferior quemada — línea detenida.',TRUNC(SYSDATE,'IW')+11,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0217','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CUT-P01'),'Cambio de cuchilla guillotina pads mascotas (cada 3M de cortes).',TRUNC(SYSDATE,'IW')+11,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0218','PREDICTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=4),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-FORM-A01'),'Análisis de aceite hidráulico del sistema de vacío adultos (laboratorio).',TRUNC(SYSDATE,'IW')+11,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0219','CORRECTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=2),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-HIL-01'),'Rodillo tensor inferior con juego excesivo — produce arrugas en spunlace.',TRUNC(SYSDATE,'IW')+11,'sistema');
COMMIT;
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0214'),1,'Bloquear LOTO eléctrico y mecánico (calce de seguridad)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0214'),2,'Extraer eje de martillos con polipasto de 2T');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0214'),3,'Instalar 4 rodamientos SKF 6310-2RS nuevos');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0214'),4,'Alinear eje con comparador de caratula (< 0.05mm)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0215'),1,'Aislar línea de proceso y drenar');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0215'),2,'Instalar sensor E+H Promag 50W y calibrar cero');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0216'),1,'Cortar alimentación del tablero empacadora');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0216'),2,'Extraer resistencia quemada (modelo HLQ-220V-1500W)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0216'),3,'Instalar resistencia nueva y verificar continuidad');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0217'),1,'Retirar cuchilla con protector de corte (EPP)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0217'),2,'Instalar cuchilla nueva y ajustar presión de corte');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0218'),1,'Tomar muestra de aceite en envase estéril');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0218'),2,'Enviar muestra a laboratorio externo para análisis viscosidad');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0219'),1,'Medir juego radial del rodillo (debe ser < 0.1mm)');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0219'),2,'Reemplazar rodamiento de rodillo tensor inferior');
COMMIT;

-- Lunes siguiente
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0220','PREVENTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=4),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-CORT-01'),'Revisión de ajuste de platinas guía y verificación de paralelismo.',TRUNC(SYSDATE,'IW')+14,'sistema');
INSERT INTO DATA.T_MTTO_ORDENES_TRABAJO (NUMERO_OT,TIPO_OT,ID_PRIORIDAD,ID_ESTADO_OT,ID_ACTIVO,DESCRIPCION,FECHA_PROGRAMADA,CREADO_POR) VALUES ('OT-2026-0221','PREDICTIVA',(SELECT ID_PRIORIDAD FROM DATA.T_MTTO_PRIORIDADES WHERE NIVEL=3),(SELECT ID_ESTADO_OT FROM DATA.T_MTTO_ESTADOS_OT WHERE CODIGO='OPEN'),(SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-MIX-01'),'Inspección visual de revestimiento interno del tanque (pinhole check).',TRUNC(SYSDATE,'IW')+14,'sistema');
COMMIT;
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0220'),1,'Medir paralelismo de platinas con galga de espesores');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0221'),1,'Inspección interior con endoscopio industrial');
INSERT INTO DATA.T_MTTO_CHECKLIST_OT (ID_OT,SECUENCIA,DESCRIPCION) VALUES ((SELECT ID_OT FROM DATA.T_MTTO_ORDENES_TRABAJO WHERE NUMERO_OT='OT-2026-0221'),2,'Fotografiar y registrar cualquier punto de corrosión');
COMMIT;

-- ============================================================
-- PASO 8: SOLICITUDES CORRECTIVAS
-- ============================================================

INSERT INTO DATA.T_MTTO_SOLICITUDES (ID_ACTIVO, DESCRIPCION_FALLA, PRIORIDAD_SUGERIDA, REPORTADO_POR)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-SAP-01'),
    'Tubo dosificador tapado intermitentemente. Los pañales salen con bajo SAP.', 'Critica', 'pedro_operador');
INSERT INTO DATA.T_MTTO_SOLICITUDES (ID_ACTIVO, DESCRIPCION_FALLA, PRIORIDAD_SUGERIDA, REPORTADO_POR)
VALUES ((SELECT ID_ACTIVO FROM DATA.T_MTTO_ACTIVOS WHERE CODIGO_ACTIVO='MQ-HIL-01'),
    'Cuchilla Spunlace mellada, hace corte imperfecto en la tela húmeda.', 'Media', 'maria_qa');

COMMIT;

-- ============================================================
-- VERIFICACIÓN FINAL
-- ============================================================
SELECT 'T_MTTO_ACTIVOS'         AS TABLA, COUNT(*) AS REGISTROS FROM DATA.T_MTTO_ACTIVOS         UNION ALL
SELECT 'T_MTTO_PUNTOS_MEDICION',           COUNT(*)              FROM DATA.T_MTTO_PUNTOS_MEDICION  UNION ALL
SELECT 'T_MTTO_PLANES',                    COUNT(*)              FROM DATA.T_MTTO_PLANES           UNION ALL
SELECT 'T_MTTO_REPUESTOS_PLAN',            COUNT(*)              FROM DATA.T_MTTO_REPUESTOS_PLAN   UNION ALL
SELECT 'T_MTTO_ORDENES_TRABAJO',           COUNT(*)              FROM DATA.T_MTTO_ORDENES_TRABAJO  UNION ALL
SELECT 'T_MTTO_CHECKLIST_OT',              COUNT(*)              FROM DATA.T_MTTO_CHECKLIST_OT     UNION ALL
SELECT 'T_MTTO_SOLICITUDES',               COUNT(*)              FROM DATA.T_MTTO_SOLICITUDES      UNION ALL
SELECT 'T_ERP_REPUESTOS_VW',               COUNT(*)              FROM DATA.T_ERP_REPUESTOS_VW
ORDER BY 1;
