-- ============================================================
-- CONFIGURACIÓN SSO: MÓDULO MANTENIMIENTO ZAIMELLA
-- Schema: DATA   CODIGOMODULO = 'MTTO'
-- Ejecutar conectado al schema DATA (o con permisos de FILES)
-- ============================================================
-- NOTA: Los triggers TG_ADMI_MODULOPAGINA y TG_ADMI_ROLACCESOS
-- asignan el ID automáticamente desde SQ_ADMI_MODULOPAGINA y
-- SQ_ADMI_ROLACCESOS. NO incluir ID en los INSERTs.
-- ============================================================

-- PASO 0: DIAGNÓSTICO PREVIO
-- SELECT * FROM DATA.T_ADMI_MODULO WHERE CODIGO = 'MTTO';
-- SELECT ID, NOMBRE FROM DATA.T_ADMI_ROL WHERE ESTADO = 1 ORDER BY ID;
-- SELECT ID, CODIGOUSUARIO, ID_ROL FROM DATA.T_ADMI_ROLUSUARIO
--  WHERE CODIGOMODULO = 'MTTO' AND ESTADO = 1;

-- ============================================================
-- PASO 1: Registrar páginas del módulo en T_ADMI_MODULOPAGINA
--
-- CODIGOPAGINA  max 9 chars (VARCHAR2(9))  → identificador corto
-- CODIGOACCION en T_ADMI_ROLACCESOS        → nombre completo (VARCHAR2(50))
-- Unique constraint: (CODIGOPAGINA, CODIGOMODULO)
-- ============================================================

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'DASHBOARD', 'MTTO', 'Panel de Control Mantenimiento',
    1, '/', 1,
    'Dashboard', 'fa-tachometer-alt', NULL, 1,
    USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'ACTIVOS', 'MTTO', 'Catálogo de Activos',
    2, '/activos', 1,
    'Catálogo Activos', 'fa-industry', NULL, 1,
    USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'PLANES', 'MTTO', 'Planes de Mantenimiento',
    3, '/planes', 1,
    'Planes de Mto.', 'fa-book', NULL, 1,
    USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'USO', 'MTTO', 'Registro de Uso de Activos',
    4, '/uso', 1,
    'Registro de Uso', 'fa-tachometer-alt', NULL, 1,
    USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'PLANIFIC', 'MTTO', 'Tablero Planificador de Órdenes de Trabajo',
    5, '/planificador', 1,
    'Tablero Planificador', 'fa-calendar-alt', NULL, 1,
    USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'OTS', 'MTTO', 'Órdenes de Trabajo',
    6, '/ots', 1,
    'Órdenes de Trabajo', 'fa-clipboard-check', NULL, 1,
    USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_MODULOPAGINA (
    CODIGOPAGINA, CODIGOMODULO, DESCRIPCION,
    ORDEN, RUTAPAGINA, ESTADO,
    OPCIONMENU, ICONOCSS, CODIGOPADRE, NIVEL,
    USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    'SOLICITUD', 'MTTO', 'Buzón de Avisos Correctivos',
    7, '/solicitudes', 1,
    'Avisos Correctivos', 'fa-bell', NULL, 1,
    USER, SYSDATE, SYSDATE
);

COMMIT;

-- Verificar IDs generados — necesarios para el PASO 2:
SELECT ID, CODIGOPAGINA, DESCRIPCION, RUTAPAGINA
  FROM DATA.T_ADMI_MODULOPAGINA
 WHERE CODIGOMODULO = 'MTTO'
 ORDER BY ORDEN;

-- ============================================================
-- PASO 2: Asignar permisos por rol en T_ADMI_ROLACCESOS
--
-- Antes de ejecutar reemplazar:
--   <ID_ROL_X>           → ID del rol en DATA.T_ADMI_ROL
--   <ID_MP_DASHBOARD>    → ID obtenido en el SELECT del PASO 1 (CODIGOPAGINA='DASHBOARD')
--   <ID_MP_ACTIVOS>      → ID (CODIGOPAGINA='ACTIVOS')
--   <ID_MP_PLANES>       → ID (CODIGOPAGINA='PLANES')
--   <ID_MP_USO>          → ID (CODIGOPAGINA='USO')
--   <ID_MP_PLANIFIC>     → ID (CODIGOPAGINA='PLANIFIC')
--   <ID_MP_OTS>          → ID (CODIGOPAGINA='OTS')
--   <ID_MP_SOLICITUD>    → ID (CODIGOPAGINA='SOLICITUD')
--
-- CODIGOACCION = clave que usa la app React (VARCHAR2(50), nombre completo)
-- CODIGO_TG    = 'MTTO' (agrupa todas las entradas del módulo)
-- Unique constraint: (ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG)
--
-- Permisos: 1 = Habilitado, 0 = Deshabilitado
--   AGREGAR      → botón "Nuevo / Crear"
--   GUARDAR      → botón "Guardar / Actualizar / Aprobar"
--   ELIMINAR     → botón "Eliminar"
--   COMENTAR     → funciones de anotaciones / comentarios
--   IMPRIMIR     → exportar / imprimir
--   CANCELAR     → botón "Rechazar / Cancelar"
-- ============================================================

-- === EJEMPLO: Rol PLANIFICADOR — gestión completa ===
-- Duplicar este bloque para cada rol adicional.

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_DASHBOARD>, 'DASHBOARD', 'MTTO',
    0, 0, 0, 0, 1, 0,
    1, USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_ACTIVOS>, 'ACTIVOS', 'MTTO',
    1, 1, 0, 1, 1, 1,
    1, USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_PLANES>, 'PLANES', 'MTTO',
    1, 1, 0, 1, 1, 1,
    1, USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_USO>, 'USO', 'MTTO',
    1, 1, 0, 1, 1, 1,
    1, USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_PLANIFIC>, 'PLANIFICADOR', 'MTTO',
    0, 1, 0, 1, 1, 0,
    1, USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_OTS>, 'OTS', 'MTTO',
    0, 1, 0, 1, 1, 0,
    1, USER, SYSDATE, SYSDATE
);

INSERT INTO DATA.T_ADMI_ROLACCESOS (
    ID_ROL, ID_MODULOPAGINA, CODIGOACCION, CODIGO_TG,
    AGREGAR, GUARDAR, ELIMINAR, COMENTAR, IMPRIMIR, CANCELAR,
    ESTADO, USUARIO_AUD, FECHACREACION, FECHAMODIFICACION
) VALUES (
    <ID_ROL_PLANIFICADOR>, <ID_MP_SOLICITUD>, 'SOLICITUDES', 'MTTO',
    0, 1, 0, 1, 1, 1,
    1, USER, SYSDATE, SYSDATE
);

COMMIT;

-- ============================================================
-- VERIFICACIÓN FINAL
-- ============================================================
SELECT A.ID               AS ID_ROL,
       A.NOMBRE           AS ROL,
       MP.CODIGOPAGINA    AS PAGINA_CODIGO,
       RA.CODIGOACCION    AS PAGINA_APP,
       RA.AGREGAR, RA.GUARDAR, RA.ELIMINAR,
       RA.COMENTAR, RA.IMPRIMIR, RA.CANCELAR
  FROM DATA.T_ADMI_ROLACCESOS   RA
  JOIN DATA.T_ADMI_MODULOPAGINA MP ON RA.ID_MODULOPAGINA = MP.ID
  JOIN DATA.T_ADMI_MODULO       M  ON MP.CODIGOMODULO    = M.CODIGO
  JOIN DATA.T_ADMI_ROL          A  ON A.ID               = RA.ID_ROL
 WHERE M.CODIGO  = 'MTTO'
   AND RA.ESTADO = 1
 ORDER BY A.ID, MP.ORDEN;
